### ISSUE TITLE
mixed wordlists

### ISSUE THREAD

**Issue by gitFrank** [xeBuz/jquery-doge#1]

**Comment by xeBuz** [comment]
What do you mean with mixed wordlist?

**Comment by gitFrank** [comment]
Hallo Jesus,

i have deleted my text, because i missunderstood your plugin.
Tought the own wordlist will overwrite the default wordlist. But you 
wrote the script so that all wordlists will be mixed. Right?

Gruß
Frank

-------- Original-Nachricht --------

_Von:_ Jesus Roldan mailto:notifications@github.com
_Datum:_ 26.12.2013 18:58:08
_An:_ xeBuz/jquery-doge mailto:jquery-doge@noreply.github.com
_Betreff:_ Re: [jquery-doge] mixed wordlists (#1)

**Comment by xeBuz** [comment]
Hi!
Yes, the default mixed two wordlists
If you want, I can create a parameter for merge/not-merge the lists

Tschüss!

**Comment by gitFrank** [comment]
Hi, you are the boss, but i think nobody should change the core-file.
My call  $('body').doge({wordList:['one','two','three']});  should show 
only this list.

What would be a great thing:
Instead 'body' i want say '#myContainer' and the words are all placed in 
this container.
Is this possible?

**Comment by xeBuz** [comment]
I tried, but I use fixed position for each element and it just work fine with the body element.
It doesn't work well with absolute position or in any container
